### ISSUE TITLE
Custom User Model Support Request

### ISSUE THREAD

**Issue by CoderMungan** [CoderMungan/DjangoEssentials#1]
I would like to request the addition of a custom user model to the djangoessential library. The custom user model should allow developers to easily extend or modify the default user fields. Here are some suggested features:

- Support for additional fields like `phone_number`, `date_of_birth`, etc.
- Integration with Django's built-in authentication and permissions system.
- Easy migration from Django's default user model.

This would enhance the flexibility and usability of the library for developers working on various projects.

**Comment by crabcatcher0** [comment]
I removed those update_at and created_at fields
