### ISSUE TITLE
Assistance Needed: NoneType Error with MyS3Storage in DjangoEssentials.

### ISSUE THREAD

**Issue by crabcatcher0** [CoderMungan/DjangoEssentials#5]
When I try to add a new object through the Django admin interface, I'm getting the following error:
TypeError: expected string or bytes-like object, got 'NoneType' 
After some debugging, I found that the params['Bucket'] is being set to None in the validate_bucket_name function.
Bucket is None: {'Bucket': None, 'Key': 'media/images/my_image.png'}
With the DEFAULT_FILE_STORAGE is set to DjangoEssentials.storage.MyS3Storage in settings.py. However, it seems like the bucket name isn’t being passed correctly, which is causing the error.

**Comment by mciray** [comment]
Yes,You're right.We will change the readme.If you want to use s3 bucket your setup need to be like this:
```
USE_S3 = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
if USE_S3:
    # aws settings
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    # s3 public media settings
    PUBLIC_MEDIA_LOCATION = 'media'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3Boto3Storage'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]
```

**Comment by crabcatcher0** [comment]
Thank You.

**Comment by CoderMungan** [comment]
your welcome <3
